name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "CUDA ${{ matrix.cuda }} / ${{ matrix.label }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            cuda: "13.2"
            label: "Windows"
            upload_nupkgs: true
          
          - os: ubuntu-latest
            cuda: "13.2"
            label: "Linux"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: "" # Use base environment
          use-mamba: true          # Highly recommended for speed on both OSs

      - name: Install NVRTC
        shell: bash -el {0}
        run: |
          conda install -c nvidia "cuda-nvrtc-dev=${{ matrix.cuda }}.*" -y
          echo $CONDA_PREFIX
          find $CONDA_PREFIX
          echo "CUDA_PATH=$CONDA_PREFIX" >> $GITHUB_ENV

      # Set up .NET SDKs
      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x

      - name: Build
        shell: bash
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Test
        shell: bash
        run: |
          dotnet run --project KernelSharp.Tests/KernelSharp.Tests.csproj -c Release --no-build

      - name: Pack
        shell: bash
        run: |
          dotnet pack -c Release --no-build -o ./nupkgs

      - name: Validate nupkg
        shell: bash
        run: |
          dotnet build -c Release NupkgValidator/NupkgValidator.csproj

      - name: Upload NuGet packages
        if: matrix.upload_nupkgs == true
        uses: actions/upload-artifact@v7
        with:
          name: nupkgs
          path: ./nupkgs
