name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "CUDA ${{ matrix.cuda }} / ${{ matrix.label }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025
            label: "VS 17 2022"
            cuda: "13.2.0"

          - os: windows-2025-vs2026
            label: "VS 18 2026"
            cuda: "13.2.0"

          # Linux
          - os: ubuntu-latest
            label: "Linux gcc"
            cuda: "13.2.0"
            pack: true # This job will be responsible for packing and uploading the NuGet packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CUDA Toolkit ${{ matrix.cuda }}
        uses: Jimver/cuda-toolkit@v0.2.35
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda }}
          method: network
          use-github-cache: true

      - name: Dump info
        shell: bash
        run: |
          echo "CUDA Version: ${{ steps.cuda-toolkit.outputs.version }}"
          echo "CUDA Path: ${{ steps.cuda-toolkit.outputs.path }}"
          printenv

      - name: Build
        shell: bash
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Test
        shell: bash
        run: |
          dotnet test -c Release --no-build

      - name: Pack
        shell: bash
        run: |
          dotnet test -c Release --no-build
  
      - name: Pack
        if: matrix.pack == true
        shell: bash
        run: |
          dotnet restore
          dotnet pack -c Release --no-build -o ./nupkgs

      - name: Upload NuGet packages
        if: matrix.pack == true
        uses: actions/upload-artifact@v3
        with:
          name: nupkgs
          path: ./nupkgs
